project_id = "vdukytnyzotybtcjzaub"

[functions.create-voucher]
verify_jwt = true

[functions.send-booking-confirmation]
verify_jwt = true

[functions.send-booking-reminders]
verify_jwt = true

[functions.send-cancellation-confirmation]
verify_jwt = true

[functions.send-voucher-expiry-alerts]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[auth]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
